### ISSUE TITLE
hey jay, i have question

### ISSUE THREAD

**Issue by nola29385** [jamescoxon/rai_quarry_pool#1]
before i install the pool I need to do this 2 things?
1.get ubuntu vps maybe 8gm ram / 8cpu
2.install python 3

yes?
thank you:)

**Comment by jamescoxon** [comment]
Hey,
I actually run the test pool on the cheapest digitalocean droplet which is 1 processor and 512mb of ram with some swap, you probably need about 2gb of ram and 2 cpu for good efficiency.

**Comment by nola29385** [comment]
thank you:)
I did step step and after screen I receive worker failed:
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
ImportError: No module named 'app'
[2017-05-04 08:15:42 +0000] [5726] [INFO] Worker exiting (pid: 5726)
[2017-05-04 08:15:42 +0000] [5723] [INFO] Shutting down: Master
[2017-05-04 08:15:42 +0000] [5723] [INFO] Reason: Worker failed to boot.

you know about this problem?

**Comment by jamescoxon** [comment]
It seems to be that gunicorn can load up modules in the wrong order, i just set the pool up on Amazon for someone and it just worked, make sure you are running gunicorn in the main directory (rai_quarry_pool).

**Comment by nola29385** [comment]
yes working, I just receive same answer on stackoverflow. thank you very much!:)
